### ISSUE TITLE
Extensions to User and Org tables -- and how to handle custom fields

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#376]
In order to create the templates required by Valerio for creating a company and applying for licences, the User and Org tables need more information (e.g. Phone number, place of birth, Professional ID Number, etc.)

Need to discuss what new columns to add, but also how to handle "Custom" fields, as every installation will be different.

To-do:

- [ ] Agree on a schema and means of extending with Custom data (e.g. JSON field for additional info?)
- [ ] Implement schema
- [ ] Check that all user/org info is retrieved and saved in local state on login
- [ ] Update User and Org registration templates to input additional information

**Comment by andreievg** [comment]
It seems this is a big part of the system that's been postponed.

What I was thinking is something like this:

* modifyRecords action (maybe better named as createOutcome, based on this suggestion), does a bit more
  * creates table if doesn't exist
  * create fields if they dont' exist
  * able to save full response
  * able to link to application
* outcomes route that shows outcomes, and .. yep, you guessed it, it's configurable, check out the diagram.
   * show cards of all of the outcomes
   * show when card is pressed show a table
   * when table element is pressed show details for that record (this shows summary views)
 
This diagram is not very good, but should describe the basic concept: https://app.diagrams.net/#G1y76nr7TnYXpLs2u32Aj4xr-92mhKzA8y

I did a proof of concept implementation `outcomes-proof-of-concept` branch of back end and front end. To see it working, have to create a new user, and then go to `/outcomes` route, click through to the newly created user. (should be able to navigate to application)

Changes

 * modifyRecord does as per above, creates table, and fields and join to an application (the database info view is from the new snapshot functionality, which I am slow to PR)
 * added an upload identification form element
 * outcomes are configured for one table (user), with table view and details view
 * have to use dynamic query building (similar to lookup table functionality).

I can explain this tomorrow.

Btw we don't need to add any extra information local state on login (and don't think we needed extra fields that were added for user edit, we can do graphQL query for defaults)

**Comment by CarlosNZ** [comment]
Sounds good. Look forward to discussing. Couple of things to consider:

- Are we sure having a dynamic schema is a good idea with GraphQL/Postgraphile? How quickly after creating a field on a table does it "appear" in Postgraphile for querying, and is it reliable? (Maybe you've tried?)
- "dynamic query building" -- strongly discouraged by GraphQL people. Can we achieve what we want with static queries and variable objects?\

So just wondering what the advantages of having dynamic schema changes are as opposed to having just few "core" fields and storing additional "custom data" in JSON objects?
