### ISSUE TITLE
Misc Snapshot/Template Builder bugs

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#506]
Just summarising these all in one place as they're probably all fairly minor fixes (I hope):

### Done Sprint 48:
- [x]  ~~Permission Policy selector/display not showing the correct thing~~
![Screen Shot 2021-08-12 at 5 19 15 PM](https://user-images.githubusercontent.com/5456533/129166404-bbcaedb6-07f2-4536-b129-d5c605f71040.png)
- [x] Files not being imported from snapshots. It seems to just be the ones in subfolders -- the 4 default icons seem to come across okay. Here's a snapshot with some logo files to test import: 
[demo_master_02.zip](https://github.com/openmsupply/application-manager-server/files/6974025/demo_master_02.zip)
- [x] ~~False alarm on the Zipped files problem~~
- [x]  ~~Show fields in UI to allow changing: isLinear, namePlural, eventCode (IMPORTANT)~~
- [x] ~~Bug: Open element and change isRequired = **false** and save. Reopen and it gets changes automatically to isRequired = **true**~~
- [x] Bug: templateAction descriptions don't get imported when using import template
- [x] ~~Template builder evaluator UI should allow the "type" property to be set~~
- [x] Small fix - can't set "canMakeDecision" on review level for Final Decision in the Permissions tab on Template builder PR https://github.com/openmsupply/application-manager-web-app/pull/948
- [x] Small fix - fields `scheduledEventCode` getting set with `description` value on UI - doesn't seem to replace real eventCode... PR https://github.com/openmsupply/application-manager-web-app/pull/936
- [x] Small fix - When setting the "Start Message" to empty, it stores an empty string -- NULL would be better (empty string still works so not super critical, it'd just be more consistent with what the front-end expects) PR https://github.com/openmsupply/application-manager-web-app/pull/953
- [x] BUG: Snapshot imports with lookup tables in schema are failing (Add lookup table, export whole snapshot, then re-import => error!)
- [x] Template export is exporting ALL files, should only do the ones associated with this template
- [x] Nice to have - "Add action" at the begin or end of the list to avoid having to click to move all the way to the top PR https://github.com/openmsupply/application-manager-web-app/pull/957
- [x] Show selected page when moving page up/down PR https://github.com/openmsupply/application-manager-web-app/pull/963

**Comment by CarlosNZ** [comment]
> * Need to add ability to add new permissionName
> 
> * Need to add ability to easily move element between pages and pages between sections
> 
> * Allow to remove template version from project

Hmm, I feel like these three are probably more involved than just "quick fixes", and could probably do with their own issues. (maybe, @andreievg would probably know better)

**Comment by andreievg** [comment]
> 12. Need to allow to change the AVAILABLE template even with existing applications linked to a previous version. This would be required to update a template.
 
That's possible now (need to make existing available to disable first, there should be a comment on hover about this)

> 11. Template builder evaluator UI should allow the "type" property to be set

Hmm, not sure about this, it's selectable (or can change to json view/edit)

**Comment by andreievg** [comment]
> Bug: click to add element and app breaks - isFirstElement check (it's ok after reloading the page)

Hmm can't replicate, tried a few times, would be good to know the exact message and log from console

**Comment by andreievg** [comment]
> Bug: templateAction descriptions don't get imported when using import template

Couldn't replicate, but found an issue, after import, when trying to edit template before server restarts (need to fix on server end, no need to restart server when templates are imported
