### ISSUE TITLE
Misc tweaks for next demo update

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#530]
Use this as an ongoing list of small things we should change before next demo build

(Most of these should be small enough that we can just push them straight to develop, no need for PR)

- [ ] Turn Scheduled Action check of "test" mode (so it checks once per hour, not every 30 seconds)
- [ ] Change application name on Login page
- [x] Typos in Company License (see below) - in latest snapshot demo-master-20
- [ ] Hide 'No Organisation' from first page of Company Registration application
- [ ] Unwrap Company License section header (or at least make the column a lot wider)

**Comment by adamdewey** [comment]
Couple of minor typos: 

![image](https://user-images.githubusercontent.com/19318937/130549208-b9eb3f06-d7ea-409a-a567-eb220e73ad76.png)

**Comment by adamdewey** [comment]
Login screen says IRIMS, next page says mFlow: 

![image](https://user-images.githubusercontent.com/19318937/130554515-18db39ca-4018-454c-99fa-8799f2e9599c.png)

![image](https://user-images.githubusercontent.com/19318937/130554524-29c6006d-643c-4f75-88b4-0dd92ae7fd37.png)

**Comment by CarlosNZ** [comment]
> Login screen says IRIMS, next page says mFlow:

Yeah, that's already on the list:

> Change application name on Login page

;)

**Comment by adamdewey** [comment]
D'oh - sorry! 🤦

**Comment by adamdewey** [comment]
![image](https://user-images.githubusercontent.com/19318937/130559091-ed6668bc-cd6e-464f-92c1-18432bddbada.png)

**Comment by adamdewey** [comment]
- [ ] Unwrap Company License section header (or at least make the column a lot wider)

![image](https://user-images.githubusercontent.com/19318937/130717868-8e69059e-9627-41bf-ae4d-c00c79bbcd2b.png)

**Comment by nmadruga** [comment]
> Hide 'No Organisation' from first page of Company Registration application
> 
> ![image](https://user-images.githubusercontent.com/19318937/130559091-ed6668bc-cd6e-464f-92c1-18432bddbada.png)

That was the suggestion from the Designer - so it's clear when you are submitting as a company.
So when there is no company you think it would be better to show empty? That's a very easy fix, should worth a try.

**Comment by adamdewey** [comment]
> That was the suggestion from the Designer - so it's clear when you are submitting as a company.
> So when there is no company you think it would be better to show empty? That's a very easy fix, should worth a try.

Yeah I think it's good when the user has a company, but for this special case of registering a company it would be neater if it was hidden :)

**Comment by nmadruga** [comment]
Cool - I think I have addresses the remaining issues listed here in these PRs: front-end & back-end

 ✅  Turn Scheduled Action check of "test" mode (so it checks once per hour, not every 30 seconds)
 Change application name on Login page
![Screen Shot 2021-08-25 at 6 57 59 PM](https://user-images.githubusercontent.com/16461988/130743476-5ad0de17-1cc2-4b68-89ad-b48354b72021.png)

 ✅  Typos in Company License (see below) - in latest snapshot demo-master-20

🥇 Hide 'No Organisation' from first page of Company Registration application
🥈 Unwrap Company License section header (or at least make the column a lot wider)
<img width="1068" alt="Screen Shot 2021-08-25 at 7 14 44 PM" src="https://user-images.githubusercontent.com/16461988/130743879-d5e804f3-ca4a-4b98-9083-46c1bb9f46f2.png">

💎  Refine language for Company Registration box in dashboard: Option A
![Screen Shot 2021-08-25 at 6 43 51 PM](https://user-images.githubusercontent.com/16461988/130744166-a38a3c7b-7975-4270-9197-32cf81aee90b.png)

**Comment by adamdewey** [comment]
Looks fab!
