### ISSUE TITLE
Misc issues/improvements found on first demo presentation

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#559]
### Sprint 49:
- [x] Can still assign stage after submitted - fixed in PR #545 & https://github.com/openmsupply/application-manager-web-app/pull/943
- [x] Outcome changing to REJECT on changes requested back to assessor on ProdRegistration. [Comment with explanation](https://github.com/openmsupply/application-manager-server/issues/559#issuecomment-914988822)
- [x] Would be very important to have “forget my password” feature - Issue: https://github.com/openmsupply/application-manager-web-app/issues/966
- [x] Outcome details not opening for all items in the list - **PR** https://github.com/openmsupply/application-manager-web-app/pull/968

### Sprint 50:
- [x] Using number fields with buttons validation fails - Issue: https://github.com/openmsupply/application-manager-web-app/issues/964 PR https://github.com/openmsupply/application-manager-web-app/pull/986
- [x] https://github.com/openmsupply/application-manager-server/issues/579 PR https://github.com/openmsupply/application-manager-server/pull/580
- [x] Ability to re-assign (even after a self-assignment) - Issue: #475 PR https://github.com/openmsupply/application-manager-web-app/pull/982 & https://github.com/openmsupply/application-manager-server/pull/574

### Sprint 51:
- [x] Filter to view re-submitted applications not working - Explanation In Jira (Not a bug)
- [x] #587 PRs https://github.com/openmsupply/application-manager-web-app/pull/997 https://github.com/openmsupply/application-manager-web-app/pull/1000
- [x] Size of form too big (probably due to zoom) on Experience element in Company licence after adding email - In Jira and PR https://github.com/openmsupply/application-manager-web-app/pull/1003
- [ ] Uploading one document and trying to go next validation fails Issue https://github.com/openmsupply/application-manager-web-app/issues/985 **WIP**

### Sprint 52:
- [ ] Need to ensure changing active template version doesn't affect applications in progress - Issue https://github.com/openmsupply/application-manager-web-app/issues/965
- [ ] https://github.com/openmsupply/application-manager-web-app/issues/950

**Comment by nmadruga** [comment]
### Outcome changing to REJECT on changes requested back to assessor on ProdRegistration

Problem due to a misconfiguration of CORE-ACTION to changeOutcome on the last stage and last level of a review ON_REVIEW_SUBMIT. The problem was with the condition as described below (didn't consider case of Changes request submitted to another reviewer:
```

{
 "operator": "AND",
 "children": [
  {
   "operator": "!=",
   "children": [
    {
     "operator": "objectProperties",
     "children": [
      "applicationData.reviewData.latestDecision.decision"
     ]
    },
    "LIST_OF_QUESTIONS"
   ]
  },
  {
   "operator": "objectProperties",
   "children": [
    "applicationData.reviewData.isLastLevel"
   ]
  },
  {
   "operator": "objectProperties",
   "children": [
    "applicationData.reviewData.isLastStage",
    null
   ]
  }
 ]
}
``` 

Changed the condition to:
```
{
 "operator": "AND",
 "children": [
  {
   "operator": "=",
   "children": [
    {
     "operator": "objectProperties",
     "children": [
      "applicationData.reviewData.latestDecision.decision",
      null
     ]
    },
    {
     "operator": "OR",
     "type": "string",
     "children": [
      "CONFORM",
      "NON_CONFORM"
     ]
    }
   ]
  },
  {
   "operator": "objectProperties",
   "children": [
    "applicationData.reviewData.isLastLevel"
   ]
  },
  {
   "operator": "objectProperties",
   "children": [
    "applicationData.reviewData.isLastStage",
    null
   ]
  }
 ]
}
```

And submitted the change to templates: `ProdRegistration-15`, `OrgRegistration-22` and `CompanyLicence-19` in folder `demo` on repo: https://github.com/openmsupply/application-manager-templates/tree/main/demo . Also I'm going to update other templates with the fix on the Core-action so the bug isn't going to happen if we copy from those templates.

**Comment by CarlosNZ** [comment]
> And submitted the change to templates: `ProdRegistration-15`, `OrgRegistration-22` and `CompanyLicence-19` on the private repo: https://github.com/openmsupply/application-manager-templates/tree/main/demo . Also I'm going to update other templates with the fix on the Core-action so the bug isn't going to happen if we copy from those templates.

Great, thanks for fixing that one. You probably want to update the "basic_snapshot" too, right?
